// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCocN8nW0K4_L8_e8UsbDk5C2_YHYDHutc',
    appId: '1:184370486783:web:93303cb14c461c3ab49bca',
    messagingSenderId: '184370486783',
    projectId: 'instagram-clone-7127d',
    authDomain: 'instagram-clone-7127d.firebaseapp.com',
    storageBucket: 'instagram-clone-7127d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOg-bc7ttzRNge-ZhhdOPwix6H6jAZFk',
    appId: '1:184370486783:android:b49fb20540cb5f4bb49bca',
    messagingSenderId: '184370486783',
    projectId: 'instagram-clone-7127d',
    storageBucket: 'instagram-clone-7127d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2J_HbBsHWTcFYFdorqifCUkMfGwUAJ4U',
    appId: '1:184370486783:ios:e7eec06754b550c0b49bca',
    messagingSenderId: '184370486783',
    projectId: 'instagram-clone-7127d',
    storageBucket: 'instagram-clone-7127d.appspot.com',
    iosClientId: '184370486783-a3bkrru48u144dji72ah8j8ig58h8auf.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
