// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgPlDwrxaHItse-gvGDmOwOvgKjGX8BWE',
    appId: '1:531021182654:web:a8d92db9f53215908310ef',
    messagingSenderId: '531021182654',
    projectId: 'twitchclone-84440',
    authDomain: 'twitchclone-84440.firebaseapp.com',
    storageBucket: 'twitchclone-84440.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2SwYD6NOSX_Kr0fbuSudS1HbbW57nLAk',
    appId: '1:531021182654:android:1de9083fcab4a13c8310ef',
    messagingSenderId: '531021182654',
    projectId: 'twitchclone-84440',
    storageBucket: 'twitchclone-84440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWESunhBpeMij0UGUjxjsSCeNaJNtNHrc',
    appId: '1:531021182654:ios:adf60171f7a8dc418310ef',
    messagingSenderId: '531021182654',
    projectId: 'twitchclone-84440',
    storageBucket: 'twitchclone-84440.appspot.com',
    iosClientId: '531021182654-42h0urg2rgfmu5m59i3794obtm7r8ijp.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWESunhBpeMij0UGUjxjsSCeNaJNtNHrc',
    appId: '1:531021182654:ios:adf60171f7a8dc418310ef',
    messagingSenderId: '531021182654',
    projectId: 'twitchclone-84440',
    storageBucket: 'twitchclone-84440.appspot.com',
    iosClientId: '531021182654-42h0urg2rgfmu5m59i3794obtm7r8ijp.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitchClone',
  );
}
